version: '3.8'

services:
  nginx:
    image: docker.io/indigobelgrade/stanovi-nginx:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: docker.io/indigobelgrade/stanovi-api:latest 
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_UPLOAD_FOLDER=${CLOUDINARY_UPLOAD_FOLDER}
    ports:
      - "3000:3000"

  frontend:
    image: docker.io/indigobelgrade/stanovi-frontend:latest
    restart: always
    depends_on:
      - api

volumes:
  postgres_data:
